package com.hss.downloader.download.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hss.downloader.download.DownloadInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DOWNLOAD_INFO".
*/
public class DownloadInfoDao extends AbstractDao<DownloadInfo, String> {

    public static final String TABLENAME = "DOWNLOAD_INFO";

    /**
     * Properties of entity DownloadInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Url = new Property(0, String.class, "url", true, "URL");
        public final static Property FilePath = new Property(1, String.class, "filePath", false, "FILE_PATH");
        public final static Property Status = new Property(2, int.class, "status", false, "STATUS");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Dir = new Property(4, String.class, "dir", false, "DIR");
        public final static Property ErrMsg = new Property(5, String.class, "errMsg", false, "ERR_MSG");
        public final static Property TotalLength = new Property(6, long.class, "totalLength", false, "TOTAL_LENGTH");
        public final static Property CreateTime = new Property(7, long.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(8, long.class, "updateTime", false, "UPDATE_TIME");
    }


    public DownloadInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DownloadInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DOWNLOAD_INFO\" (" + //
                "\"URL\" TEXT PRIMARY KEY NOT NULL ," + // 0: url
                "\"FILE_PATH\" TEXT," + // 1: filePath
                "\"STATUS\" INTEGER NOT NULL ," + // 2: status
                "\"NAME\" TEXT," + // 3: name
                "\"DIR\" TEXT," + // 4: dir
                "\"ERR_MSG\" TEXT," + // 5: errMsg
                "\"TOTAL_LENGTH\" INTEGER NOT NULL ," + // 6: totalLength
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 7: createTime
                "\"UPDATE_TIME\" INTEGER NOT NULL );"); // 8: updateTime
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_DOWNLOAD_INFO_FILE_PATH ON \"DOWNLOAD_INFO\"" +
                " (\"FILE_PATH\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_DOWNLOAD_INFO_UPDATE_TIME ON \"DOWNLOAD_INFO\"" +
                " (\"UPDATE_TIME\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DOWNLOAD_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DownloadInfo entity) {
        stmt.clearBindings();
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(1, url);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(2, filePath);
        }
        stmt.bindLong(3, entity.getStatus());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String dir = entity.getDir();
        if (dir != null) {
            stmt.bindString(5, dir);
        }
 
        String errMsg = entity.getErrMsg();
        if (errMsg != null) {
            stmt.bindString(6, errMsg);
        }
        stmt.bindLong(7, entity.getTotalLength());
        stmt.bindLong(8, entity.getCreateTime());
        stmt.bindLong(9, entity.getUpdateTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DownloadInfo entity) {
        stmt.clearBindings();
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(1, url);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(2, filePath);
        }
        stmt.bindLong(3, entity.getStatus());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String dir = entity.getDir();
        if (dir != null) {
            stmt.bindString(5, dir);
        }
 
        String errMsg = entity.getErrMsg();
        if (errMsg != null) {
            stmt.bindString(6, errMsg);
        }
        stmt.bindLong(7, entity.getTotalLength());
        stmt.bindLong(8, entity.getCreateTime());
        stmt.bindLong(9, entity.getUpdateTime());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public DownloadInfo readEntity(Cursor cursor, int offset) {
        DownloadInfo entity = new DownloadInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // url
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // filePath
            cursor.getInt(offset + 2), // status
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // dir
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // errMsg
            cursor.getLong(offset + 6), // totalLength
            cursor.getLong(offset + 7), // createTime
            cursor.getLong(offset + 8) // updateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DownloadInfo entity, int offset) {
        entity.setUrl(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setFilePath(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStatus(cursor.getInt(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDir(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setErrMsg(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTotalLength(cursor.getLong(offset + 6));
        entity.setCreateTime(cursor.getLong(offset + 7));
        entity.setUpdateTime(cursor.getLong(offset + 8));
     }
    
    @Override
    protected final String updateKeyAfterInsert(DownloadInfo entity, long rowId) {
        return entity.getUrl();
    }
    
    @Override
    public String getKey(DownloadInfo entity) {
        if(entity != null) {
            return entity.getUrl();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DownloadInfo entity) {
        return entity.getUrl() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
